# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will build, test, sign and package a WPF or Windows Forms desktop application
# built on .NET Core.
# To learn how to migrate your existing application to .NET Core,
# refer to https://docs.microsoft.com/en-us/dotnet/desktop-wpf/migration/convert-project-from-net-framework
#
# To configure this workflow:
#
# 1. Configure environment variables
# GitHub sets default environment variables for every workflow run.
# Replace the variables relative to your project in the "env" section below.
#
# 2. Signing
# Generate a signing certificate in the Windows Application
# Packaging Project or add an existing signing certificate to the project.
# Next, use PowerShell to encode the .pfx file using Base64 encoding
# by running the following Powershell script to generate the output string:
#
# $pfx_cert = Get-Content '.\SigningCertificate.pfx' -Encoding Byte
# [System.Convert]::ToBase64String($pfx_cert) | Out-File 'SigningCertificate_Encoded.txt'
#
# Open the output file, SigningCertificate_Encoded.txt, and copy the
# string inside. Then, add the string to the repo as a GitHub secret
# and name it "Base64_Encoded_Pfx."
# For more information on how to configure your signing certificate for
# this workflow, refer to https://github.com/microsoft/github-actions-for-desktop-apps#signing
#
# Finally, add the signing certificate password to the repo as a secret and name it "Pfx_Key".
# See "Build the Windows Application Packaging project" below to see how the secret is used.
#
# For more information on GitHub Actions, refer to https://github.com/features/actions
# For a complete CI/CD sample to get started with GitHub Action workflows for Desktop Applications,
# refer to https://github.com/microsoft/github-actions-for-desktop-apps

name: .NET Core Desktop

on:
  push:
    branches: [ "release" ]
  pull_request:
    branches: [ "release" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]
        platform: [x64, arm64]

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    env:
      Solution_Name: DynamicWin.sln
      DWAppVersion: v1.6.0r

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Install Inno Setup
      run: choco install innosetup --no-progress -y

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    # Execute all unit tests in the solution
    - name: Execute unit tests
      run: dotnet test

    # Restore the application to populate the obj folder with RuntimeIdentifiers
    - name: Restore the application
      run: msbuild $env:Solution_Name /t:Restore /p:Configuration=$env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}

    - name: Publish application
      run: msbuild DynamicWin/DynamicWin.csproj `
           /t:Publish `  
           /p:Configuration=Release `
           /p:Platform=${{ matrix.platform }} `
           /p:RuntimeIdentifier=win-${{ matrix.platform }} `
           /p:SelfContained=false `
           /p:PublishDir=${{ github.workspace }}\publish\Release-${{ matrix.platform }}\

    - name: List published files
      run: dir publish\Release-${{ matrix.platform }}\

    - name: Build installer
      run: |
        iscc Other\DynamicWin-Legacy-Setup.iss `
        /DDWAppVersion=${{ env.DWAppVersion }} `
        /DPlatform=${{ matrix.platform }}

    - name: Generate SHA256 and MD5 hashes
      run: |
        $installer = "Other\Output\DynamicWinSetup-${{ matrix.platform }}.exe"

        $dir = Split-Path $installer
        if (-not (Test-Path $dir)) {
            New-Item -ItemType Directory -Path $dir | Out-Null
        }

        if (Test-Path $installer) {
            Get-FileHash $installer -Algorithm SHA256 | ForEach-Object { $_.Hash } | Out-File "$installer.sha256"
            Get-FileHash $installer -Algorithm MD5    | ForEach-Object { $_.Hash } | Out-File "$installer.md5"
        } else {
            Write-Error "Installer not found: $installer"
        }

    - name: Upload artefacts
      uses: actions/upload-artifact@v4
      with:
        name: DynamicWin-${{ matrix.platform }}
        path: |
            Other\Output\DynamicWinSetup-${{ matrix.platform }}.exe
            Other\Output\DynamicWinSetup-${{ matrix.platform }}.exe.sha256
            Other\Output\DynamicWinSetup-${{ matrix.platform }}.exe.md5

    - name: Generate release notes
      run: |
        $notes = @"
# What is new in v1.6.0r
- Dedicated installers for both `x64` and `arm64` devices
- New island/notch design shape adjustment
- Topmost placement fixes
- Font adjustment (again... from `Satoshi` to `SF Pro Display`)
- New progress bar implementation (deprecates `DWProgressBar.cs`)
- Bug fixes and improvements (mainly with `InteropServices` calls on `MediaController.cs`)

> [!NOTE]
> _This update was intended to be released as `v1.5.1r`, but there are a lot of changes made to the point where it did not make sense anymore to consider publishing this as a minor update. Therefore this update will be released as `v1.6.0r`._

### Dedicated installers for both `x64` and `arm64` Windows devices
Starting with **`v1.6.0r`**, DynamicWin-Legacy installers are now provided in both `x64` and `arm64` binaries!
While `arm64` devices are still allowed to install `x64` binaries, both options are provided regardless. However, it is recommended to install the binaries according to the device's specifications.

> [!WARNING]
> These release builds are now automated and are provided immediately the moment a new version is pushed to the `release` branch. Know that installations may not work, so please report these inconsistencies on the [issues page](https://github.com/59xa/DynamicWin-Legacy/issues).

### Visual upgrades on island/notch
With **`v1.6.0r`**, the island/notch goes through another makeover once again!
This update converts the sharp edges for both island/notch modes to use squircles as the superellipse pathing, making the overlay look more fancy. Other UI elements also received this same treatment as part of this change.

The overlay's font also receives an adjustment to use `SF Pro Display` instead of `Satoshi`.

\`AudioVisualiser.cs` gets an adjustment again... this time with rendering the sample frequencies properly by no longer keeping ranges per bar, making output and feel more accurate and similar to the dynamic island on iPhones.

If `displayDotWhenIdle` setting is set to true, bar output will be consistent by clamping the lower volume output to the shape of a dot instead of going further down.

### Topmost adjustments
Previously, I mentioned that topmost was to be removed for this update. Good news, it is here to stay but with constraints.
For applications like `MyDockFinder`, the overlay will be forced down. Suggest using alternatives like `Droptop 4` instead.

### Progress bar adjustments
As of this update, `DWProgressBar.cs` is deprecated in preference of `DWProgressBarEx.cs`.
This change also affects `DWSlider.cs`, and this new implementation will be used across all UI elements that use the progress bar.

### Bug fixes and improvements
With the release of `v1.5.0r1`, there were performance issues that caused the CPU usage to spike up mainly when fetching metadata from `MediaController.cs`.
This new update addresses that issue, please continue to report performance degradation through the [issues page](https://github.com/59xa/DynamicWin-Legacy/issues) or in the Discord server.

### Future of DynamicWin-Legacy
While updates are still being pushed out for DynamicWin-Legacy, expect the updates to stagnate as this repository slowly reaches end-of-life in the coming months.
The good news, however, is that DynamicWin-Legacy will be superseded by a new project in the works! More information about this soon; but for now, V3 is confirmed.

### Continued support:
- Your support truly means a lot to me as I continue to maintain DynamicWin-Legacy. Keep an eye out on this repository whenever a new release comes out.
- Feel free to contribute to this project as you wish. Open any issues on the issues page if you encounter any bugs.

### Checksums:
\`\`\`
SHA256: 
MD5: 
\`\`\`
        "@
        $notes | Out-File release_notes.md -Encoding UTF8

    - name: Create Github Release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ env.DWAppVersion }}
        name: DynamicWin-Legacy ${{ env.DWAppVersion }} [${{ matrix.platform }}]
        bodyFile: release_notes.md
        artifacts: |
            Other\Output\DynamicWinSetup-x64.exe
            Other\Output\DynamicWinSetup-x64.exe.sha256
            Other\Output\DynamicWinSetup-x64.exe.md5
            Other\Output\DynamicWinSetup-arm64.exe
            Other\Output\DynamicWinSetup-arm64.exe.sha256
            Other\Output\DynamicWinSetup-arm64.exe.md5
        draft: true
        prerelease: false
        skipIfReleaseExists: true
        replacesArtifacts: true